### ISSUE TITLE
Error in 1:nrow(results$matched$index) : argument of length 0

### ISSUE THREAD

**Issue by uros-sipetic** [chrisamiller/fishplot#1]
Hi
I am testing out Fishplot, my usual pipeline is SciClone -> ClonEvol -> Fishplot, using the script for generating fishplot results based on ClonEvol data listed on the github frontpage. 
So far it was running ok, but for one set of files I got the following error:

Error in 1:nrow(results$matched$index) : argument of length 0

The run wasn't any different than the runs for the other data I had. 
Would if help in any way if I sent or attached the ClonEvol Rdata file, for debugging purposes?

**Comment by chrisamiller** [comment]
Did clonevol successfully infer one or more models for the data? If not,
then there will be nothing to plot.

I f you're unsure, please paste the commands you're using and any output
(errors/warnings) from your session.

On Sep 15, 2016 7:08 AM, "uros-sipetic" notifications@github.com wrote:

Hi
I am testing out Fishplot, my usual pipeline is SciClone -> ClonEvol ->
Fishplot, using the script for generating fishplot results based on
ClonEvol data listed on the github frontpage.
So far it was running ok, but for one set of files I got the following
error:

Error in 1:nrow(results$matched$index) : argument of length 0

The run wasn't any different than the runs for the other data I had.
Would if help in any way if I sent or attached the ClonEvol Rdata file, for
debugging purposes?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/chrisamiller/fishplot/issues/1, or mute the thread

**Comment by uros-sipetic** [comment]
Hi
The commands I used for ClonEvol are also directly from the github page example. 
This is my output from ClonEvol

***WARN: Inra-tumor heterogeneity could result in a clone (eg. founding)
         that is not present (no cells) in any samples, although  detectable via
         clonal marker variants due to that its subclones are distinct across
         samples. Therefore, a model with a higher p-value for the CCF of such
         a clone can still be biologically consistent, interpretable, and
         interesting! Manual investigation of those higher p-value models
         is recommended
No compatible multi-sample models provided.
                Individual sample models will be plotted!
Loading required package: grid
sh: 1: convert: not found
Warning messages:
1: Removed 2851 rows containing missing values (geom_point). 
2: Removed 2730 rows containing missing values (geom_point). 
3: Removed 2673 rows containing missing values (geom_point). 

So yeah, this could be an issue because the data I used is just some example data I got somewhere, so it could be that the data doesn't make sense.

**Comment by chrisamiller** [comment]
Yep. This is the key phrase: No compatible multi-sample models provided.
