### ISSUE TITLE
Cannot determine the parents?

### ISSUE THREAD

**Issue by ghost** [chrisamiller/fishplot#14]
I have a fraction table which is given below where I input all the VAFS for each gene. Timepoints set as c(0,300,500,700,1500)days. But unable to set the parents values.
frac .table 
47	9	38	44	02
53	6	19	39	14
02	02	02	02	02
02	02	02	02	02
60	23	0	26	27
35	22	0	31	59
41	28	0	39	63
45	22	0	50	90
Kindly advise me to set the parents.
Error:
Error in validateInputs(frac.table, parents, nest.level, clone.labels) : 
  Clone 5 goes from present to absent (fraction=0) and then back to present. Values for which the cluster was present must be non-zero. Either fix the inputs or set fix.missing.clones=TRUE to change offending timepoints to very small values.

**Comment by chrisamiller** [comment]
I can't tell you that answer. You're going to have to either use a tool like ClonEvol (https://github.com/hdng/clonevol) to reconstruct the phylogeny, or figure out possible models by hand. That will tell you the parental relationships.

The error you're receiving is because if a clone is absent and then reappears, it couldn't have truly been gone.  Instead of zeros, set the values for those clones to a very small number.
