### ISSUE TITLE
Giant clone fractions appearing and disappearing

### ISSUE THREAD

**Issue by sandmanns** [chrisamiller/fishplot#20]
Hi Chris,

I run into a problem using fishplot in the "spline" mode. 
When defining 2 time points (but it also happens when using more points), the displayed fraction at the points is perfectly correct. But in between, the latest clones appear with fractions that don't seem right. This is an example, where the 8th clone goes from 22 to a giant fraction (>100) and then finally to 0. 

timepoints=c(0,100)
frac.table=matrix(
    c(72,0,
      68,0,
      60,0,
      54,0,
      50,0,
      46,0,
      36,0,
      22,0),
    ncol=length(timepoints),byrow=T)
parents = c(0,1,2,3,4,5,6,7)
fish = createFishObject(frac.table,parents,timepoints=timepoints)
fish = layoutClones(fish)
fishPlot(fish,shape="spline",title.btm="Test",cex.title=1.5, vlines=c(0,100))

![test](https://user-images.githubusercontent.com/30867840/55227958-17e42b00-5219-11e9-840f-f64b6e2ebd57.png)

Interestingly, this problem does not appear when working with just 7 clones, so e.g. removing former clone number 7:

frac.table=matrix(
    c(72,0,
      68,0,
      60,0,
      54,0,
      50,0,
      46,0,
      22,0),
    ncol=length(timepoints),byrow=T)
parents = c(0,1,2,3,4,5,6)

![test2](https://user-images.githubusercontent.com/30867840/55228003-43671580-5219-11e9-9a1c-635c20b00674.png)

Everything is fine in "polygon"-mode, but I would really like to use "spline".
I already tried adding additional time points, but this only shifts the problem to the right or left of the plot. The giant fraction unfortunately remains.

It would be great if you could help me with this issue!

Thanks a lot in advance,
Sarah

**Comment by chrisamiller** [comment]
That's a new one to me!  I've looked into it and it seems that it arises because of two things:

1) each successive clone has to get closer and closer to the "0" line
2) the splining function has constraints on how sharp it can make the angle of a curve, so that it's still "smooth"

When a certain threshold is reached (which happens to coincide with n=8 for subclones here), it has to swing that curve out wide to fulfill its constraints.  Some possible solutions:

a) add "pad.left=0.4" to your "fishplot" command. That will give the subclones some more room to operate
b) you might be able to add additional "fake" timepoints that force the curve into a more sane space
c) you could muck around with the internals of the package to force the curves to fit more tightly.  Specifically lowering the value of the `flank`  value in the `drawClustSpline` function might help, as might changing the params on the actual `spline()` command being used.

Also, I'm certainly open to pull requests if you find a generalizable solution that improves this edge case - Best of luck!

**Comment by sandmanns** [comment]
Thanks a lot!
For now, "pad.left=0.4" is a really good solution!
If I find the time, I will have a more detailed look at the `drawClusterSpline` function and let you know in case I find something.

Thanks again!
