### ISSUE TITLE
Input data clarification

### ISSUE THREAD

**Issue by l0ka** [chrisamiller/fishplot#27]
Hello Chris,

I'm trying the fishplot package on simulated data but I'm not sure I correctly understood how to prepare the input data.
Let's say I have data for 2 time points, primary tumor and first relapse; I estimated the cancer cell fractions (CCFs) values and clustered them. The resulting CCFs table is:
```
primary   relapse   cluster   is.clonal
1.0          1.0          C1        TRUE       # clonal alterations
1.0          0.0          C2        FALSE      # primary specific alterations
0.5          1.0          C3        FALSE      # shared subclonal alterations
0.0          1.0          C4        FALSE      # relapse specific subclonal alterations
0.0          0.3          C5        FALSE      # relapse specific subclonal alterations
```
And the clonal tree is:
```
\--Normal
   \--C1
    |---C3
    | \---C4
    |  \---C5
    |
    \---C2
```
So, in order to run fishplot, I guess I should prepare the `frac.table` in this way:
```
timepoints <- c(1, 2)

parents    <- c(0, 1, 2, 3)

frac.table <- matrix(data = c(100, 50,  0,   0,
                              100, 100, 100, 30),
                     ncol = length(timepoints)
                     )
```
Is that correct?
Another question I have is: clones C4 and C5 are barely visible in the plot, it looks like they are "compressed" toward the right side. Is there a way to enhance the visualization?
Thank you!

**Comment by chrisamiller** [comment]
Your tree is a bit confusing to me, as I don't think the fractions add up.  If C3 is not derived from C2 (and they can't be because C2 goes to 0, while C3 persists), then the sum of their percentages can't exceed 100in the primary. (If C2 takes up 100% of the tumor, then there's "no room" for an extra 50% from C3).  Once you get that resolved, I imagine it may help you get the plotting pushed through.
