### ISSUE TITLE
Adding VAF(%) y-axis to Fishplots

### ISSUE THREAD

**Issue by esoyfer** [chrisamiller/fishplot#37]
Hello Chris,
Hope all is well. Is there a way in the fishplot package to add a y-axis (for VAF, variant allele frequency) to a fishplot, such as in the following paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5762372/
Thank you,
Eli

**Comment by chrisamiller** [comment]
Since fishplots are centered vertically and "bulge" out in both directions, the y-axes used in that paper are useless (at best) or misleading (at worst). It's certainly possible to envision a y-axis that either extends in both directions, or a modified fishplot that isn't centered, but rises up from the bottom. I have no plans to implement either, though, as in my mind, fishplots are meant to be more qualitative than quantitative in the information they present.  If you want to compare VAFs at different timepoints, a line or barplot might be best.  

See Figures 2 and 3 in this paper if you're looking for some inspiration. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5880262/  Hope this helps!
